#!/usr/bin/env python3
"""Generate docs/model_zoo.md — one model card per trained campaign checkpoint.

Reads the per-run evaluation.json files under results/trained/*/ and produces a
zoo page with a summary table plus a card per checkpoint (architecture, seeds,
benchmark metrics, download pointer). Checkpoints themselves are large and
git-ignored; they are distributed as a GitHub Release / HF Hub artifact, and the
cards link to that.

Usage:
  python scripts/generate_model_cards.py --release-tag v0.1.0
"""
from __future__ import annotations

import argparse
import glob
import json
import re
from pathlib import Path

REPO = "mathi0405/drone-swarm-sar"


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--glob", default="results/trained/*/evaluation.json")
    ap.add_argument("--release-tag", default="v0.1.0")
    ap.add_argument("--out", default="docs/model_zoo.md")
    args = ap.parse_args()

    cards = []
    for p in sorted(glob.glob(args.glob)):
        run = Path(p).parent.name
        m = re.match(r"([a-z_]+)_s(\d+)_", run)
        if not m:
            continue
        arch, seed = m.group(1), int(m.group(2))
        agg = json.loads(Path(p).read_text(encoding="utf-8")).get("aggregate", {})
        def g(k, _agg=agg):
            v = _agg.get(k, {})
            return v["mean"] if isinstance(v, dict) else float("nan")
        cards.append({
            "run": run, "arch": arch, "seed": seed,
            "sis": round(g("swarm_intelligence_score"), 1),
            "rescued": round(g("victims_rescued"), 2),
            "coverage": round(g("coverage"), 2),
            "collision": round(g("collision_rate"), 4),
            "ckpt": f"results/trained/{run}/checkpoints/best.pt",
        })
    cards.sort(key=lambda c: (c["arch"], c["seed"]))

    dl = f"https://github.com/{REPO}/releases/download/{args.release_tag}"
    lines = [
        "# Model zoo", "",
        "Trained MAPPO checkpoints from the 3M-step campaign, evaluated on the",
        "frozen 20-map benchmark (utility-based SIS). Checkpoints are released as",
        f"assets on [{args.release_tag}](https://github.com/{REPO}/releases/tag/{args.release_tag}).",
        "This page is generated by `scripts/generate_model_cards.py`.", "",
        "| Checkpoint | Arch | Seed | SIS | Rescued /8 | Coverage | Collisions/step |",
        "|------------|------|-----:|----:|-----------:|---------:|----------------:|",
    ]
    for c in cards:
        lines.append(f"| `{c['run']}` | {c['arch']} | {c['seed']} | **{c['sis']}** | "
                     f"{c['rescued']} | {c['coverage']} | {c['collision']} |")
    lines += ["", "## Load a checkpoint", "",
              "```python",
              "from swarm_sar.policies import load_policy",
              "policy = load_policy('best.pt')   # rebuilds arch + critic mode from metadata",
              "```", "",
              "Or evaluate directly:", "",
              "```bash",
              f"# download an asset from the {args.release_tag} release, then:",
              "python scripts/evaluate.py --ckpt best.pt --out results/eval.json",
              "```", ""]
    for c in cards:
        lines += [
            f"## `{c['run']}`", "",
            f"- **Architecture:** {c['arch']}  ·  **Seed:** {c['seed']}",
            f"- **Benchmark SIS:** {c['sis']}  ·  **Rescued:** {c['rescued']}/8  ·  "
            f"**Coverage:** {c['coverage']}  ·  **Collisions/step:** {c['collision']}",
            "- **Training:** MAPPO, 3M steps, CTDE (shared policy, centralized critic), "
            "performance-gated curriculum",
            f"- **Download:** [`{c['run']}_best.pt`]({dl}/{c['run']}_best.pt)", "",
        ]
    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[OK] wrote {args.out} with {len(cards)} model cards")


if __name__ == "__main__":
    main()
