#!/usr/bin/env python3
"""Regenerate the benchmark leaderboard from evaluation JSON files.

Reads one or more evaluate.py-style result files (each maps a method/checkpoint
name to an ``aggregate`` metric dict) and emits docs/leaderboard.md — a ranked
table on the frozen 20-map benchmark under the utility-based SIS.  New entries
are added by dropping a results JSON in results/ and re-running this script, so
the leaderboard is reproducible and PR-reviewable (see the submission protocol
in the generated page).

Usage:
  python scripts/update_leaderboard.py results/campaign_eval_utility.json [more.json ...]
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

BENCH = "SwarmSAR-Bench v1 (20 frozen maps, seeds 200-219)"


def _rows(paths: list[str]) -> list[dict]:
    rows = []
    for p in paths:
        data = json.loads(Path(p).read_text(encoding="utf-8"))
        for name, rec in data.items():
            agg = rec.get("aggregate", rec)
            def g(k, d=0.0, _agg=agg):
                v = _agg.get(k, d)
                return v["mean"] if isinstance(v, dict) else v
            label = re.sub(r"_\d{8}_\d{6}", "", Path(name).parts[-3] if "/" in name or "\\" in name else name)
            rows.append({
                "method": label,
                "sis": round(g("swarm_intelligence_score"), 1),
                "rescued": round(g("victims_rescued"), 2),
                "coverage": round(g("coverage"), 2),
                "collision": round(g("collision_rate"), 4),
                "comm_util": round(g("communication_utility", g("communication_efficiency")), 3),
                "source": Path(p).name,
            })
    # keep the best SIS per method label
    best: dict[str, dict] = {}
    for r in rows:
        if r["method"] not in best or r["sis"] > best[r["method"]]["sis"]:
            best[r["method"]] = r
    return sorted(best.values(), key=lambda r: r["sis"], reverse=True)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("results", nargs="+", help="evaluate.py JSON result files")
    ap.add_argument("--out", default="docs/leaderboard.md")
    args = ap.parse_args()

    rows = _rows(args.results)
    lines = [
        "# Benchmark & leaderboard", "",
        f"Ranked results on **{BENCH}** under the utility-based Swarm",
        "Intelligence Score (SIS). Higher is better. This page is generated by",
        "`scripts/update_leaderboard.py` — do not edit by hand.", "",
        "| Rank | Method | SIS | Rescued /8 | Coverage | Collisions/step | Comm-utility |",
        "|-----:|--------|----:|-----------:|---------:|----------------:|-------------:|",
    ]
    for i, r in enumerate(rows, 1):
        lines.append(f"| {i} | `{r['method']}` | **{r['sis']}** | {r['rescued']} | "
                     f"{r['coverage']} | {r['collision']} | {r['comm_util']} |")
    lines += [
        "", "## How the score is computed", "",
        "SIS is a weighted geometric mean over coverage, rescue, energy,",
        "communication *utility* (comm-assisted rescues + coverage uniqueness),",
        "and safety — see [Metrics & SIS](metrics.md). The geometric mean",
        "penalizes sacrificing any single dimension.", "",
        "## Submit a result", "",
        "1. Evaluate your policy on the frozen benchmark:", "",
        "   ```bash",
        "   python scripts/evaluate.py --ckpt path/to/your.pt --out results/your_method.json",
        "   ```", "",
        "2. Regenerate this table and open a pull request:", "",
        "   ```bash",
        "   python scripts/update_leaderboard.py results/*.json",
        "   ```", "",
        "3. Include in the PR: the config used, the seed count, and the",
        "   `results/your_method.json` file. Reviewers re-run `evaluate.py` to",
        "   confirm the numbers before merging — the benchmark seeds are frozen",
        "   so results are reproducible.", "",
        "!!! note \"Fair-comparison rules\"",
        "    Report at least 5 seeds. The env dynamics, reward, and the 20",
        "    benchmark maps (seeds 200-219) must be unmodified. Learned methods",
        "    must earn communication (no scripted auto-broadcast).", "",
    ]
    Path(args.out).write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[OK] wrote {args.out} with {len(rows)} entries")


if __name__ == "__main__":
    main()
